package de.thlemm.householdorganizer.model;

public enum RoomName {
    ROOM_DINING,
    ROOM_LIVING,
    ROOM_KITCHEN,
    ROOM_GARAGE,
    ROOM_OFFICE,
    ROOM_BEDROOM,
    ROOM_GREEN,
    ROOM_LOTTO,
    ROOM_LIBORI_ONE,
    ROOM_LIBORI_TWO,
    ROOM_BATH,
    ROOM_TOILET_PINK,
    ROOM_TOILET_BEIGE,
    ROOM_PANTRY,
    ROOM_HALL_GROUND_FLOOR,
    ROOM_HALL_FIRST_FLOOR,
    ROOM_HALL_SECOND_FLOOR,
    ROOM_CENTRAL_CELLAR,
    ROOM_LAUNDRY_CELLAR,
    ROOM_STORAGE_CELLAR,
    ROOM_WORKSHOP,
    ROOM_SOUTH_BALCONY,
    ROOM_NORTH_BALCONY,
    ROOM_REFER_TO_IMAGE
}
