package de.thlemm.householdorganizer.model;

public enum TransactionStatusName {
    TRANSACTION_STATUS_AVAILABLE,
    TRANSACTION_STATUS_SOLD,
    TRANSACTION_STATUS_TAKEN,
    TRANSACTION_STATUS_DISPOSED,
    TRANSACTION_STATUS_GIVEN_AWAY,
    TRANSACTION_STATUS_NOT_ASSESSED,
    TRANSACTION_STATUS_RESERVED
}
